import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { VisibilityProvider } from "@/components/VisibilityContext";

// import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/nwr6bvq.css" />
      </head>
      <body className={`bg-[#ececec] antialiased`}>

        <VisibilityProvider>{children}</VisibilityProvider>
      </body>
    </html>
  );
}
