const violao = [
  {
    id: "1",
    nome: "Violão GEWA Clássico Acústico Nylon Student VG500.140",
    oldPrice: "R$ 1.609,00",
    newPrice: "R$ 801,00",
    image: "/public/img/violaoGewa.webp",
    informações:
      "A série GEWA STUDENT representa a entrada perfeita no mundo dos violões acústicos com uma excelente relação entre preço e desempenho. Fatores como o perfil do braço e a ação das cordas, que são cruciais para a tocabilidade, estão perfeitamente ajustados. Os violões são leves e bem equilibradas. Um papel importante é desempenhado pelo braço feito de madeira okoumé, cujo reforço interno de carbono estabiliza essa área sensível. O verniz eco-mate à base de água proporciona uma sensação agradável e contribui significativamente para o caráter sonoro aberto dos instrumentos, pois o tratamento de poros abertos permite que a madeira vibre com mais liberdade. Cordas Hannabach 815HT feitas na Alemanha são instaladas na fábrica e complementam perfeitamente o conceito sonoro desta série.",
    marca: "GEWA",
    modelo: "VG500.140",
    tampo: " Spruce",
    sobreMarca:
      "A GEWA foi fundada em 1925 por Georg Walther na “Vogtländische Musikwinkel” em Adorf. Desde então, a melhoria constante dos produtos e serviços, bem como a orientação para as necessidades individuais dos clientes, têm como prioridade máxima. A linha GEWA Pure oferece Violões para iniciantes, estudantes e profissionais. É por isso que a GEWA Pure torna a entrada no mundo da música o mais fácil e acessível possível para os músicos de amanhã.",
  },
  {
    id: "2",
    nome: "Violão Clássico Yamaha Acústico Nylon C-40 II - Natural",
    oldPrice: "R$ 899,00",
    newPrice: "R$ 809,10",
    image: "/public/img/violaoYamaha.webp",
    informações:
      "Os violões acústicos de cordas de nylon C40 tornam o processo de aprendizado o mais fácil e agradável possível. Além de seu som e tocabilidade excepcionais, esses instrumentos são realmente bonitos, e é por isso que foram escolhidos por vários iniciantes no mundo todo. Vários dos melhores professores recomendam os violões de cordas de nylon C40 para seus alunos devido à excelente combinação de alta qualidade e preço acessível.Embora seja verdade que os violões C40 são excelentes instrumentos para iniciantes, sua estrutura, som e tocabilidade impressionantes, garantem que eles continuarão a atendê-lo durante toda a sua jornada musical. Além disso, foram desenvolvidos usando o know-how e a experiência adquiridos ao projetar e construir nossos instrumentos profissionais premium, incluindo a escolha de madeiras extraordinárias que resultam em som excelente e durabilidade incrível.",
    marca: "Yamaha",
    modelo: " C-40 II",
    tampo: " Spruce",
    sobreMarca:
      "As mãos habilidosas de Torakusu Yamaha deram início à maior fábrica de instrumentos musicais do mundo. Tudo começou em 1887, quando ele criou o primeiro órgão de bambu do Japão. O desenvolvimento da arte de criar instrumentos musicais veio como uma consequência natural. Torakusu criou, anos mais tarde, a Nippon Gakki Co. Ltda, responsável pela idealização do primeiro piano japonês. Em 1904, o piano e o órgão Yamaha receberam reconhecimento mundial ao ganhar o grande prêmio na Feira Mundial de St. Louis. Atualmente, a Yamaha Musical se firmou como a maior fabricante de instrumentos musicais do mundo, somando 26 mil funcionários no total, 89 subsidiárias. Desde o ano de 1900 a empresa já vendeu 6,15 milhões de pianos. Além da liderança no mercado de instrumentos musicais, a empresa está no topo dos mercados de áudio e vídeo, equipamentos de tecnologia da informação, entre outros. A filosofia de negócios da corporação é totalmente voltada para o consumidor, por isso a criação dos produtos é detalhadamente pensada para preencher lacunas existentes nos diversos segmentos. A busca pela excelência é alcançada por meio da proximidade entre os produtos Yamaha e o potencial cliente. Dentro de uma estratégia mundial de desenvolvimento, a Yamaha apóia diversas atividades musicais, incluindo parcerias com escolas de música, realização de workshops, entre outras atividades. A idéia principal é dar suporte para a educação e popularização da música universal e local. Essa interação com o público consumidor, somada à constante incorporação de novas tecnologias, resulta em soluções que oferecem grande satisfação ao usuário, respeitando sua individualidade, criatividade e iniciativa.",
  },
  {
    id: "3",
    nome: "Violão Giannini Acústico Nylon Estudante GN-15 - Tobacco Sunburst",
    oldPrice: "R$ 679,00",
    newPrice: "R$ 611,10",
    image: "/public/img/violaoGianinni.webp",
    informações:
      "Esta série intermediária é para quem já tem alguma familiaridade com violões e busca se aprimorar. Superiores à série Start, mas extremamente acessíveis para os músicos novatos.",
    marca: "Giannini",
    modelo: " GN-15 TS",
    tampo: " Spruce",
    sobreMarca:
      "A Giannini é uma das marcas de instrumentos musicais mais tradicionais e respeitadas do Brasil. Conhecida pela qualidade e inovação, a empresa combina técnicas artesanais com tecnologias modernas para produzir uma ampla gama de instrumentos, incluindo violões, guitarras, baixos e ukuleles. Além de fabricar instrumentos de alta qualidade, a Giannini apoia a cultura musical no Brasil por meio de projetos sociais e educacionais. Reconhecida internacionalmente, a marca é sinônimo de excelência e paixão pela música, sendo a escolha de muitos músicos renomados ao redor do mundo.",
  },
  {
    id: "4",
    nome: "Violão Giannini Acústico Nylon Estudo GN-15 - Preto",
    oldPrice: "R$ 679,00",
    newPrice: "R$ 611,10",
    image: "/public/img/violaoGianinniBlack.webp",
    informações:
      "Esta série intermediária é para quem já tem alguma familiaridade com violões e busca se aprimorar. Superiores à série Start, mas extremamente acessíveis para os músicos novatos.",
    marca: "Giannini",
    modelo: " GN-15 BK",
    tampo: " Spruce",
    sobreMarca:
      "A Giannini é uma das marcas de instrumentos musicais mais tradicionais e respeitadas do Brasil. Conhecida pela qualidade e inovação, a empresa combina técnicas artesanais com tecnologias modernas para produzir uma ampla gama de instrumentos, incluindo violões, guitarras, baixos e ukuleles. Além de fabricar instrumentos de alta qualidade, a Giannini apoia a cultura musical no Brasil por meio de projetos sociais e educacionais. Reconhecida internacionalmente, a marca é sinônimo de excelência e paixão pela música, sendo a escolha de muitos músicos renomados ao redor do mundo.",
  },
  {
    id: "5",
    nome: "Violão Rozini Mini Acústico Nylon Baby 3/4 RX205 ACFI Estudante",
    oldPrice: "R$ 999,00",
    newPrice: "R$ 899,10",
    image: "/public/img/violaoRozini.webp",
    informações:
      "O Violão Rozini RX205 é um excelente instrumento, possuindo um corpo no tamanho reduzido, o que facilita no transporte e na tocabilidade, podendo até ser um ótimo presente para crianças. Feito com tampo em marfim, laterais e fundo laminado em imbuia e braço em cedro, o que traz leveza e facilidade ao toque do instrumento, além de oferecer sons firmes e timbre encorpado.",
    marca: "Rozini",
    modelo: " RX205.AC.F.I",
    tampo: " Spruce",
    sobreMarca:
      "A Rozini produz de forma artesanal Violões, Violas Caipira, Cavacos, Banjos e Bandolins, Percussão, Pandeiros e o exclusivo Tanajura, além de distribuir acessórios musicais como Tarraxas, Equalizadores, Cases, etc. É uma marca nacional, criada em meados da década de 90, por José Roberto Rozini com seu grande tino comercial, acompanhado de José Pereira, experiente Luthier, aposentado depois de 30 anos de trabalho.",
  },
  {
    id: "6",
    nome: "Violão Fender Concert Acústico Aço CC 60s - All Mahogany",
    oldPrice: "R$ 3.290,00",
    newPrice: "R$ 2.961,00",
    image: "/public/img/violaoFender.webp",
    informações:
      "Compacto e confortável, o CC-60S é ideal para músicos iniciantes. O corpo menor do tamanho de um concerto é fácil de manobrar em qualquer posição de execução, com uma voz articulada que é ótima para tocar com os dedos. Seu tampo em mahogany sólido melodioso, braço fácil de tocar e fundo e laterais em mahogany fazem do CC-60S a escolha perfeita para a praia, o pátio ou o café.",
    marca: "Fender",
    modelo: " CC-60s All-Mahogany Concert",
    tampo: "Mahogany",
    sobreMarca:
      "Os instrumentos Icônicos da Fender como a Telecaster, Stratocaster, Precision Bass e Jazz Bass são conhecidos mundialmente como os instrumentos que iniciaram a revolução do rock, e continuam a ser altamente valorizados pelos músicos e colecionadores atuais. Com uma história ilustre que antecede 1946, a Fender tem marcado e transformado a música em todo o mundo e em quase todos os gêneros musicais: rock 'n' roll, country e western, jazz, rhythm and blues e muitos outros. Todos, de iniciantes e amadores até artistas e intérpretes mais aclamados do mundo têm usado instrumentos e amplificadores Fender, tornando a empresa não só um nome de referencia na indústria da música, como também um ícone cultural.",
  },
];

const teclado = [
  {
    id: "1",
    nome: "Teclado Arranjador Casio CT-S1 FH Romero Britto 61 Teclas Sensitivas",
    oldPrice: "R$ 2.999,00",
    newPrice: "R$ 1.961,10",
    image: "/public/img/tecladoCasio1.webp",
    informações: "Casiotone e Romero Britto: Uma colaboração que incorpora a alegria de criar música com a inconfundível arte de felicidade e esperança de Romero. Acessível para qualquer pessoa, adorada por todos. O Casiotone nasceu para tornar a música acessível a todos. Romero Britto expressa sentimentos universais de esperança e felicidade através da sua arte. Dois lados da mesma aspiração, o CT-S1FH reflete nossa paixão por trazer felicidade e alegria para o maior número possível de pessoas através da música e da arte.Este é um teclado cujas cores intensas fazem com que você queira começar a tocar. Compartilhe a experiência com amigos e familiares para criar uma atmosfera musical positiva e alegre. A obra de arte, especialmente projetada por Romero Britto, comunica amor, esperança e felicidade. É divertido ter uma arte como esta à sua volta, mas é ainda mais divertido poder tocar.No centro do CT-S1, a tecnologia AiX Sound Source produz os sons e as experiências reais de cada instrumento. Os tecladistas podem escolher entre 61 tons (incluindo piano acústico, piano elétrico e órgão), cuidadosamente elaborados para serem incluídos em seus favoritos. Desenvolvidos por engenheiros especializados, os Advanced Tones da Casio permitem que você experimente a grandeza e o desempenho com muita facilidade.Analisamos o som e a estrutura de instrumentos musicais vintage usados em hits do passado e do presente para trazê-los à vida com a nossa tecnologia exclusiva. Agora, você está na banda. Incluímos até mesmo os Casio Classic Tones, permitindo que o clássico voltasse a ser novo. Captamos os sons icônicos da nossa rica linhagem de teclados e sintetizadores, como o Casiotone 201, para celebrar a estreia nos anos 1980 dos nossos instrumentos musicais eletrônicos.Aproveite sons dinâmicos com o recém-desenvolvido sistema integrado de alto-falantes do CT-S1. A inovadora tecnologia Horizontal Bass Reflex e os alto-falantes especialmente projetados proporcionam notas claras e cristalinas, com um punch de graves poderoso, em um formato elegante e compacto. Leve sua experiência de imersão musical um pouco mais além e mergulhe em uma atmosfera sonora exuberante em meio a toda a potência do som surround. Mantenha qualidade elevada de som em qualquer decibel com a função Volume-Sync EQ, que ajusta automaticamente a presença de graves e agudos, mesmo em volumes baixos.O design compacto do CT-S1 garante que a música esteja sempre ao seu lado, sendo fácil de carregar e tocar a qualquer hora e em qualquer lugar. Você não precisa se preparar. Sem problemas de armazenamento. Música e inovação sempre estarão ao seu alcance. O design slim cabe em qualquer espaço, proporcionando a você a flexibilidade de combinar seu estilo, de tocar com seu estado de espírito, se adaptando mesmo em locais mais justos. Inclui também pinos para encaixar sua correia favorita, possibilitando a liberdade de tocar sem suporte ou mesa. Não importa se você está no sofá, rodeado pela família, ou relaxando no seu quarto: toque quando e onde quiser.O CT-S1 jamais vai deixar de inspirar você. Dê vida às suas ideias criativas. Com o adaptador de áudio e MIDI sem fio WU-BT10, você pode parear seu smartphone ou tablet com o teclado e ouvir ou acompanhar suas músicas favoritas por meio do poderoso sistema de alto-falantes do CT-S1. O aplicativo CASIO MUSIC SPACE permite que você personalize suas experiências. No modo Áudio, mude o tom e ajuste o tempo. Usando os botões cancel melody ou cancel accompaniment, transforme sua música favorita em um playback e toque junto. O modo Aula utiliza o recurso MIDI para individualizar suas aulas e tornar o aprendizado divertido. Outros aplicativos com MIDI habilitado e dispositivos externos garantem que não haja limitações na experiência à medida que você explora maneiras novas e divertidas de ouvir, adaptar e criar músicas.",
    marca: "Casio",
    modelo: "CT-S1 FH",
    teclasnum: "61",
    sobreMarca: "A Casio Computer Co. Ltd. é um dos fabricantes líder no mercado mundial de produtos eletrônicos ao consumidor e de soluções de equipamentos empresariais. Desde sua fundação, em 1957, a CASIO vem trabalhando para manter o princípio de criatividade e contribuição da corporação, lançando produtos inovadores.",
  },
  {
    id: "2",
    nome: "Piano Digital Yamaha P-145 com 88 Teclas - Preto",
    oldPrice: "R$ 4.990,00",
    newPrice: "R$ 3.419,10",
    image: "/public/img/tecladoYamaha1.webp",
    informações: "O P-145 oferece o número mínimo de recursos da série P, com foco em oferecer uma experiência autêntica graças ao seu design simples e facilidade de uso. Comparado com seu antecessor, o novo P-145 apresenta um design de corpo muito mais curto e mais fino, com um estilo simples, porém mais moderno e compacto. Nosso recém-desenvolvido teclado GHC (Graded Hammer Compact) de 88 teclas foi construído de acordo com padrões rigorosos e oferece a mesma sensação de toque como em um piano acústico ponderado como nas teclas GHS (Graded Hammer Standard) usadas nos modelos anteriores da série P.Esse modelo apresenta o som de um piano de cauda completo para concerto, o piano CFIIIS da Yamaha: a origem dos principais pianos de cauda para concerto da Yamaha, o CFX. O som foi sampleado de um piano com um timbre brilhante e transparente, com agudos amplos e uma sensação sonora sólida de modo geral. Além disso, o P-145 apresenta uma função de ressonância do amortecedor que reproduz o som intenso de ressonância que você ouve ao pressionar o pedal do amortecedor, para um som ainda mais encorpado.O P-145 possui um design que representa perfeitamente a expressão menos é mais. O P-145 oferece funções e aspectos simples e modernos para atender às necessidades dessas pessoas.",
    marca: "Yamaha",
    modelo: "P-145",
    teclasnum: "88",
    sobreMarca: "As mãos habilidosas de Torakusu Yamaha deram início à maior fábrica de instrumentos musicais do mundo. Tudo começou em 1887, quando ele criou o primeiro órgão de bambu do Japão. O desenvolvimento da arte de criar instrumentos musicais veio como uma consequência natural. Torakusu criou, anos mais tarde, a Nippon Gakki Co. Ltda, responsável pela idealização do primeiro piano japonês. Em 1904, o piano e o órgão Yamaha receberam reconhecimento mundial ao ganhar o grande prêmio na Feira Mundial de St. Louis. Atualmente, a Yamaha Musical se firmou como a maior fabricante de instrumentos musicais do mundo, somando 26 mil funcionários no total, 89 subsidiárias. Desde o ano de 1900 a empresa já vendeu 6,15 milhões de pianos. Além da liderança no mercado de instrumentos musicais, a empresa está no topo dos mercados de áudio e vídeo, equipamentos de tecnologia da informação, entre outros. A filosofia de negócios da corporação é totalmente voltada para o consumidor, por isso a criação dos produtos é detalhadamente pensada para preencher lacunas existentes nos diversos segmentos. A busca pela excelência é alcançada por meio da proximidade entre os produtos Yamaha e o potencial cliente. Dentro de uma estratégia mundial de desenvolvimento, a Yamaha apóia diversas atividades musicais, incluindo parcerias com escolas de música, realização de workshops, entre outras atividades. A idéia principal é dar suporte para a educação e popularização da música universal e local. Essa interação com o público consumidor, somada à constante incorporação de novas tecnologias, resulta em soluções que oferecem grande satisfação ao usuário, respeitando sua individualidade, criatividade e iniciativa.",
  },
  {
    id: "3",
    nome: "Teclado Arranjador Roland E-X20 A com 61 Teclas",
    oldPrice: "R$ 2.519,00",
    newPrice: "R$ 1.889,10",
    image: "/public/img/tecladoRoland.webp",
    informações: "Se você quer ser músico, tocar teclado é o jeito mais amplo de aprender tudo sobre música. Criado pela Roland - marca admirada por profissionais no mundo todo por sua história, qualidade e expressão - o E-X20A é o instrumento perfeito pra você começar sua vida na música. Os sons de piano de alta qualidade foram feitos pra ajudar no desenvolvimento musical, onde os timbres tradicionais são sempre exigidos. Além disso, este teclado também tem outras opções de sons internos, incluindo vários sons étnicos pra tocar ritmos regionais de qualquer lugar do mundo. Tocar sozinho no E-X20A é uma experiência única – com o arranjador embutido você toca com uma seção de acompanhamento completo, te preparando pra primeira experiência com banda ou orquestra.",
    marca: "Roland",
    modelo: "E-X20A",
   teclasnum: " 61 teclas sensitivivas (com Velocity)",
    sobreMarca: "A Roland Corporation é a líder mundial no mercado de instrumentos musicais eletrônicos, incluindo teclados e sintetizadores, produtos de guitarra, percussão eletrônica, equipamentos de gravação digital, música eletrônica, amplificadores e processadores de áudio. Com mais de 40 anos de inovação que continua transformando a música moderna, a Roland define o padrão em tecnologia musical para o mundo todo. Preste atenção nos equipamentos usados pelo seus músicos favoritos, é bem provável que eles usem instrumentos Roland para criar sua música.",
  },
  {
    id: "4",
    nome: "Teclado Sintetizador Roland XPS-30 RD 61 Teclas - Vermelho",
    oldPrice: "R$ 7.559,00",
    newPrice: "R$ 5.849,00",
    image: "/public/img/tecladoRoland2.webp",
    informações: "O XPS-30 chega com os grandes recursos do popular XPS-10 e adiciona melhorias que músicos de profissionais e amadores vão amar. Sons essenciais para o palco, como os de piano acústico e elétrico, estão ainda melhores, e as formas de onda internas podem ser facilmente expansíveis com as coleções de sons grátis do site Roland Axial. A seleção de sons de instrumentos regionais também foi melhorada e mais amostras sampler podem ser importados graças à capacidade de memória dobrada. Ele tem também um sequenciador de padrão de oito tracks incluso para capturar músicas e idéias, além de uma conveniente entrada de microfone com efeitos vocais dedicados.",
    marca: "Roland",
    modelo: "XPS-30",
    teclasnum: "61 teclas",
    sobreMarca: "A Roland Corporation é a líder mundial no mercado de instrumentos musicais eletrônicos, incluindo teclados e sintetizadores, produtos de guitarra, percussão eletrônica, equipamentos de gravação digital, música eletrônica, amplificadores e processadores de áudio. Com mais de 40 anos de inovação que continua transformando a música moderna, a Roland define o padrão em tecnologia musical para o mundo todo. Preste atenção nos equipamentos usados pelo seus músicos favoritos, é bem provável que eles usem instrumentos Roland para criar sua música",
  },
  {
    id: "5",
    nome: "Teclado Sintetizador Roland XPS-30 Synth 61 Teclas - Preto",
    oldPrice: "R$ 7.559,00",
    newPrice: "R$ 5.849,00",
    image: "/public/img/tecladoRoland3.webp",
    informações: "O Sintetizador XPS-30 chega com os grandes recursos do popular XPS-10 e adiciona melhorias que músicos vão amar. Sons essenciais para o palco, como os de piano acústico e elétrico, estão ainda melhores, e as formas de onda internas podem ser facilmente expansíveis com as coleções de sons grátis do site Roland Axial. A seleção de sons de instrumentos regionais também foi melhorada e mais amostras sampler podem ser importados graças à capacidade de memória dobrada. Ele tem também um sequenciador de padrão de oito tracks incluso para capturar músicas e idéias, além de uma conveniente entrada de microfone com efeitos vocais dedicados.",
    marca: "Roland",
    modelo: "XPS-30",
    teclasnum: "61 teclas semipesadas com velocity",
    sobreMarca: "A Roland Corporation é a líder mundial no mercado de instrumentos musicais eletrônicos, incluindo teclados e sintetizadores, produtos de guitarra, percussão eletrônica, equipamentos de gravação digital, música eletrônica, amplificadores e processadores de áudio. Com mais de 40 anos de inovação que continua transformando a música moderna, a Roland define o padrão em tecnologia musical para o mundo todo. Preste atenção nos equipamentos usados pelo seus músicos favoritos, é bem provável que eles usem instrumentos Roland para criar sua música.",
  },
  {
    id: "6",
    nome: "Piano Digital Casio CDP-S160 - Vermelho",
    oldPrice: "R$ 3.429,00",
    newPrice: "R$ 2.715,65",
    image: "/public/img/tecladoCasio2.webp",
    informações: "O Casio CDP-S160 é um piano Digital com design sofisticado de estrutura fina com profundidade de apenas 23 cm. A tecnologia de montagem de alta densidade patenteada da CASIO, com componentes miniaturizados, possui estrutura interna resistente e compacta.A tecnologia de montagem de alta densidade patenteada da CASIO, com componentes miniaturizados e estrutura interna compacta, é fundamental para a estrutura compacta deste piano. Duas variações de cores estão disponíveis: preto e vermelho. O esquema de cores simples e arrojado e a estética de design minimalista proporcionam uma experiência de piano simples, mas elegante. A série CDP-S é compacta, leve e totalmente portátil. Como ele pode ser alimentado por energia CA ou baterias, você pode tocá-lo não apenas como quiser, mas também onde quiser.",
    marca: "Casio",
    modelo: "CDP-S160",
    teclasnum: " 88 teclas",
    sobreMarca: "A Casio Computer Co. Ltd. é um dos fabricantes líder no mercado mundial de produtos eletrônicos ao consumidor e de soluções de equipamentos empresariais. Desde sua fundação, em 1957, a CASIO vem trabalhando para manter o princípio de criatividade e contribuição da corporação, lançando produtos inovadores.",
  },
];
const instrumentos = [
  violao,
  teclado,
];
export instrumentos